//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marinin2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accumulator
    {
        public int Id { get; set; }
        public int ManufacturerId { get; set; }
        public int VoltageId { get; set; }
        public int BatteryCapacityId { get; set; }
        public int AccumulatorLengthId { get; set; }
        public int AccumulatorWidthId { get; set; }
        public int AccumulatorHeightId { get; set; }
        public int AccumulatorSeriesId { get; set; }
    
        public virtual AccumulatorLength AccumulatorLength { get; set; }
        public virtual AccumulatorWidth AccumulatorWidth { get; set; }
        public virtual AccumulatorHeight AccumulatorHeight { get; set; }
        public virtual AccumulatorSery AccumulatorSery { get; set; }
        public virtual BatteryCapacity BatteryCapacity { get; set; }
        public virtual AccumulatorManufacturer AccumulatorManufacturer { get; set; }
        public virtual Voltage Voltage { get; set; }
    }
}
