//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marinin2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accumulator> Accumulators { get; set; }
        public virtual DbSet<AccumulatorHeight> AccumulatorHeights { get; set; }
        public virtual DbSet<AccumulatorLength> AccumulatorLengths { get; set; }
        public virtual DbSet<AccumulatorManufacturer> AccumulatorManufacturers { get; set; }
        public virtual DbSet<AccumulatorSery> AccumulatorSeries { get; set; }
        public virtual DbSet<AccumulatorWidth> AccumulatorWidths { get; set; }
        public virtual DbSet<ACEA> ACEAs { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<API> APIs { get; set; }
        public virtual DbSet<BatteryCapacity> BatteryCapacities { get; set; }
        public virtual DbSet<Composition> Compositions { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DepartureET> DepartureETs { get; set; }
        public virtual DbSet<DiameterOfTheCenteralHole> DiameterOfTheCenteralHoles { get; set; }
        public virtual DbSet<Disk> Disks { get; set; }
        public virtual DbSet<DisksDiameter> DisksDiameters { get; set; }
        public virtual DbSet<DisksWidth> DisksWidths { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<LoadIndex> LoadIndexes { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<NumberOfMountingHole> NumberOfMountingHoles { get; set; }
        public virtual DbSet<OEM> OEMs { get; set; }
        public virtual DbSet<Oil> Oils { get; set; }
        public virtual DbSet<OilType> OilTypes { get; set; }
        public virtual DbSet<SpeedIndex> SpeedIndexes { get; set; }
        public virtual DbSet<Tire> Tires { get; set; }
        public virtual DbSet<TiresDiameter> TiresDiameters { get; set; }
        public virtual DbSet<TiresHeight> TiresHeights { get; set; }
        public virtual DbSet<TiresRadiu> TiresRadius { get; set; }
        public virtual DbSet<TiresWidth> TiresWidths { get; set; }
        public virtual DbSet<Viscosity> Viscosities { get; set; }
        public virtual DbSet<Voltage> Voltages { get; set; }
    }
}
