//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marinin2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disk
    {
        public int Id { get; set; }
        public int DisksWidthId { get; set; }
        public int DisksDiameterId { get; set; }
        public int DiameterOfTheCenteralHoleId { get; set; }
        public int DepartureET_Id { get; set; }
        public int NumberOfMountingHolesId { get; set; }
    
        public virtual DepartureET DepartureET { get; set; }
        public virtual DiameterOfTheCenteralHole DiameterOfTheCenteralHole { get; set; }
        public virtual DisksDiameter DisksDiameter { get; set; }
        public virtual DisksWidth DisksWidth { get; set; }
        public virtual NumberOfMountingHole NumberOfMountingHole { get; set; }
    }
}
