//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marinin2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tire
    {
        public int Id { get; set; }
        public int TiresRadiusId { get; set; }
        public int TiresDiameterId { get; set; }
        public int LoadIndexId { get; set; }
        public int SpeedIndexId { get; set; }
        public int TiresWidthId { get; set; }
        public int TiresHeightId { get; set; }
    
        public virtual LoadIndex LoadIndex { get; set; }
        public virtual SpeedIndex SpeedIndex { get; set; }
        public virtual TiresDiameter TiresDiameter { get; set; }
        public virtual TiresHeight TiresHeight { get; set; }
        public virtual TiresRadiu TiresRadiu { get; set; }
        public virtual TiresWidth TiresWidth { get; set; }
    }
}
